site_name: NH Switch Guide - Modifed by ELY M. 
theme: cyborg
copyright: Copyright &copy; 2019 Nintendo Homebrew, <a href="/about">About this guide</a>.
site_description: NH Switch CFW Guide - Modifed by ELY M. 
site_author: NH Discord Server. - Modifed by ELY M.

nav:
    - Home: index.md
    - User Guide:
        - 'Getting Started': 'user_guide/getting_started.md'
        - 'RCM': 'user_guide/rcm.md'
        - 'SD preparations': 'user_guide/emummc/sd_preparation.md'        
        - 'Entering RCM': 'user_guide/emummc/entering_rcm.md'
        - 'Sending a payload': 'user_guide/emummc/sending_payload.md'        
        - 'Partitioning the SD and Making emuMMC': 'user_guide/emummc/partitioning_sd_and_making_emummc.md'    
        - 'Launching CFW': 'user_guide/emummc/launching_cfw.md'      
    - Extras:
        - 'Troubleshooting': 'extras/troubleshooting.md' 
        - 'NAND Backup': 'extras/nandbackup.md'        
        - 'Blocking Updates': 'extras/blocking_updates.md'
        - 'Ban Risks': 'extras/banrisks.md'  
        - 'Incognito': 'extras/incognito.md'         
        - 'Reinstalling Atmosphere': 'extras/reinstall.md'
        - 'Backing up and restoring emuMMC': 'extras/backup_restore_emummc.md'        
        - 'Restoring a NAND Backup': 'extras/nandrestore.md'
        - 'AutoRCM': 'extras/autorcm.md'
        - 'Dumping Title Keys': 'extras/dumping_title_keys.md'
        - 'Theming': 'extras/theming.md'
        - 'Save Management': 'extras/save_management.md'
        - 'Game Cheating': 'extras/cheating.md' 
        - 'Tesla Overlay': 'extras/tesla_overlay.md'         
        - 'Game Modding': 'extras/game_modding.md'       
        - 'Sigpatches': 'extras/sigpatches.md' 
        - 'Installing nsps over USB': 'extras/installing_nsps_via_usb.md'           
        - 'Lan Play': 'extras/lanplay.md'       
        - 'Linux injection without root': 'extras/adding_udev.md'
        - 'Showing File Name Extensions (Windows)': 'extras/showing_file_extensions.md'
        - 'Alternate Boot Setups': 'extras/alternate_bootsetups.md'
        - 'RCM Payload Injectors Information': 'extras/rcm_injectors.md'
        - 'Updating CFW': 'extras/updating.md'
        - 'Changing SD cards': 'extras/transfer_sd.md'
        - 'CFW Comparsion': 'cfw_comparsion.md'
        - 'Glossary': 'extras/glossary.md'
    - FAQ: faq.md
    - About: about.md
    - Elys Stuff:
        - 'My Atmosphere Tips': 'elystips.md'
        - 'My Reasons and Faqs': 'elysfaq.md'
        - 'SMO Modding': 'smo_modding.md' 
        - 'Elys Switch Homebrews on github': 'https://github.com/topics/elys-switch-homebrew'

plugins:
    - markdownextradata
    
markdown_extensions:
    - admonition
    - fontawesome_markdown

extra_css:
    - css/custom.css

extra:
  versions:
    firmware: 12.0.2
    atmosphere: 0.19.3   

