site_name: Switch Guide - Modded by ELY M. 
theme: cyborg
copyright: Copyright &copy; 2019 Nintendo Homebrew, <a href="/about">About this guide</a>.
site_description: Switch CFW Guide - Modifed by ELY M. 
site_author: NH Discord Server. - Modifed by ELY M.

nav:
    - Home: index.md
    - User Guide:
        - 'Getting Started': 'user_guide/getting_started.md'
        - 'RCM': 'user_guide/rcm.md'        
        - 'Entering RCM': 'user_guide/emummc/entering_rcm.md'
        - 'Sending a payload': 'user_guide/emummc/sending_payload.md'        
        - 'Partitioning the SD': 'user_guide/emummc/partitioning_sd.md'    
        - 'SD preparations': 'user_guide/emummc/sd_preparation.md'
        - 'Making the emuMMC': 'user_guide/emummc/making_emummc.md'
        - 'Launching CFW': 'user_guide/emummc/launching_cfw.md'
    - Extras:
        - 'Blocking Updates': 'extras/blocking_updates.md'
        - 'Ban Risks': 'extras/banrisks.md'        
        - 'Reinstalling Atmosphere': 'extras/reinstall.md'
        - 'Backing up and restoring emuMMC': 'extras/backup_restore_emummc.md'        
        - 'Restoring a NAND Backup': 'extras/nandrestore.md'
        - 'AutoRCM': 'extras/autorcm.md'
        - 'Dumping Title Keys': 'extras/dumping_title_keys.md'
        - 'Theming': 'extras/theming.md'
        - 'Save Management': 'extras/save_management.md'
        - 'Game Cheating': 'extras/cheating.md' 
        - 'Game Modding': 'extras/game_modding.md'       
        - 'Sigpatches': 'extras/sigpatches.md' 
        - 'Lan Play': 'extras/lanplay.md'         
        - 'Linux injection without root': 'extras/adding_udev.md'
        - 'Showing File Name Extensions (Windows)': 'extras/showing_file_extensions.md'
        - 'Alternate Boot Setups': 'extras/alternate_bootsetups.md'
        - 'RCM Payload Injectors Information': 'extras/rcm_injectors.md'
        - 'Updating CFW': 'extras/updating.md'
        - 'Glossary': 'extras/glossary.md'
    - FAQ: faq.md
    - About: about.md
    - Elys Stuff:
        - 'My Atmosphere Tips': 'elystips.md'
        - 'My Reasons and Faqs': 'elysfaq.md'
        - 'SMO Modding': 'smo_modding.md' 
        - 'Elys Switch Homebrews on github': 'https://github.com/topics/elys-switch-homebrew'
    
markdown_extensions:
    - admonition
    - fontawesome_markdown

extra_css:
    - css/custom.css
